### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Dinos-Ano** [course-dprep/team-project-team_6#17]
Update the motivation part and the research questions

**Comment by bram-teunissen** [comment]
Will find a new linear model

**Comment by vscanturk** [comment]
@Dinos-Ano can you also update about page?
<img width="340" alt="Screen Shot 2023-10-04 at 13 41 57" src="https://github.com/course-dprep/team-project-team_6/assets/143270096/b4464ae4-ddd5-45d1-a5fc-992eb227ec35">
