### ISSUE TITLE
Add links to the ReadMe

### ISSUE THREAD

**Issue by Dinos-Ano** [course-dprep/team-project-team_6#18]
Links are needed for the ReadMe part.

The readme is not a copy of your way of deployment (e.g., your report), but links to it. Therefore, only summarize the main results in your readme (e.g., in bullet point format), or include screenshots (e.g., to your app, to your “best” figure).

**Comment by vscanturk** [comment]
@bram-teunissen  updated the Read me already, I'll be adding a control variable for host_since to our updated research question
